repos:
  - repo: local
    hooks:
      - id: cspell-resume
        name: cspell resume.yaml
        entry: cspell resume.yaml
        language: system
        pass_filenames: false
        always_run: true
